"use client";
import {useEffect,useState} from "react";
type A=Record<string,string|string[]>;type Q={id:string;n:number;t:string;h?:string;p?:string;type?:"single"|"multi"|"grouped";o?:string[];groups?:{name:string;o:string[]}[];req?:boolean;max?:number;other?:boolean;none?:string;featured?:boolean;desc?:string[]};
const S:{name:string;label:string;intro:string;q:Q[]}[]=[
{name:"Sobre o negócio",label:"Primeiro passo",intro:"Primeiro, quero conhecer um pouco melhor o que você está construindo. Não precisa ter tudo definido ainda — responda do seu jeito.",q:[
{id:"q1",n:1,t:"Me conta um pouquinho sobre a empresa que você está criando.",h:"Como surgiu a ideia de abrir seu próprio escritório? O que te motivou a começar?",p:"Pode responder do seu jeito — não precisa ser uma resposta longa.",req:true},
{id:"q2",n:2,t:"Quais serviços você pretende oferecer?",type:"multi",req:true,other:true,o:["Contabilidade para empresas","Abertura e regularização de empresas","Fiscal e tributário","Folha de pagamento / Departamento Pessoal","Consultoria contábil","Planejamento tributário","Atendimento para MEI e autônomos","Outro","Ainda estou definindo"]},
{id:"q3",n:3,t:"Quem você mais imagina atendendo?",type:"multi",req:true,other:true,o:["Pequenas empresas","Prestadores de serviço","Profissionais autônomos","Profissionais da saúde","Comércio","Empresas digitais","Empresas de diferentes segmentos","Ainda não defini","Outro"]},
{id:"q4",n:4,t:"Como você imagina que será o atendimento?",type:"grouped",req:true,groups:[{name:"Formato",o:["Online","Presencial","Os dois","Ainda não defini"]},{name:"Alcance",o:["Mais local ou regional","Diferentes regiões do Brasil","Brasil inteiro","Ainda não sei"]}]},
{id:"q5",n:5,t:"O que você gostaria que um cliente encontrasse no seu escritório que normalmente não encontra em outros?",h:"Pense na forma de atender, explicar, acompanhar, resolver problemas, agilidade ou proximidade.",p:"Eu gostaria que meus clientes encontrassem...",req:true,featured:true}]},
{name:"A personalidade",label:"Como ela deve ser percebida",intro:"Agora quero entender como você gostaria que essa empresa fosse percebida pelas pessoas.",q:[
{id:"q6",n:6,t:"Escolha até 4 palavras que mais combinam com a empresa que você quer construir.",h:"Escolha até 4.",type:"multi",req:true,max:4,other:true,o:["Confiável","Moderna","Próxima","Ágil","Estratégica","Sofisticada","Humana","Clara","Tecnológica","Tradicional","Inovadora","Segura","Simples","Séria","Acessível","Organizada","Outra palavra"]},
{id:"q7",n:7,t:"Agora o contrário: o que você NÃO gostaria que sua empresa parecesse?",type:"multi",other:true,o:["Antiquada","Engessada","Fria","Genérica","Informal demais","Distante","Complicada","Impessoal","Popular demais","Conservadora demais","Outro"]},
{id:"q8",n:8,t:"Pensando no futuro, o que mais combina com os seus planos para a empresa?",h:"Pode escolher mais de uma opção. E tudo bem se você ainda não tiver pensado tão longe.",type:"multi",req:true,o:["Ter uma carteira mais selecionada e um atendimento próximo","Crescer e formar uma equipe","Atender clientes de todo o Brasil","Atender empresas maiores","Expandir para consultoria e outros serviços","Ter uma estrutura física","Tornar-se uma marca reconhecida no segmento","Ainda não pensei tão longe"]}]},
{name:"O nome",label:"Naming",intro:"Você não precisa chegar aqui sabendo exatamente o que quer. Estas perguntas existem para eu entender quais caminhos fazem mais sentido.",q:[
{id:"q9",n:9,t:"Você comentou sobre o nome “CONTIMA”. Como essa ideia surgiu?",h:"Existe algum significado, combinação ou história? Se foi só uma ideia que apareceu, tudo bem também.",p:"A ideia surgiu...",req:true},
{id:"q10",n:10,t:"Hoje, como você se sente em relação a CONTIMA?",type:"single",req:true,o:["É só uma ideia","Gosto, mas quero comparar","Gosto bastante"],desc:["Podemos explorar outros caminhos livremente.","Quero conhecer outras possibilidades antes de decidir.","Gostaria que ele fosse considerado entre os principais caminhos."]},
{id:"q11",n:11,t:"Sobre a relação do nome com contabilidade, o que você prefere?",type:"single",req:true,o:["Quero algo que lembre contabilidade de forma mais clara","Pode ter uma relação mais sutil","Pode ser um nome mais conceitual","Não sei — quero conhecer caminhos diferentes"]},
{id:"q12",n:12,t:"Que tipo de nome costuma chamar mais a sua atenção?",h:"Escolha até 3. Não precisa pensar especificamente em contabilidade.",type:"multi",req:true,max:3,o:["Curto e fácil de lembrar","Forte e corporativo","Moderno","Sofisticado","Tradicional","Humano e próximo","Diferente e autoral","Simples de pronunciar","Com um significado por trás","Não sei ainda"]},
{id:"q13",n:13,t:"Existe alguma coisa que seria especial trazer para o nome?",h:"Pode ser uma palavra, sobrenome, inicial, lugar, história pessoal ou conceito importante.",p:"Escreva aqui o que gostaria de explorar...",none:"Não tenho nada específico em mente.",req:true},
{id:"q14",n:14,t:"Existe alguma coisa que você definitivamente NÃO gostaria no nome?",h:"Pode ser uma palavra, estilo, idioma, sonoridade ou algo parecido com outras empresas.",p:"Escreva aqui o que devemos evitar...",none:"Não tenho nenhuma restrição.",req:true}]}
];
const KEY="briefing-naming-v2";
// Endpoint do Formspree — respostas chegam direto no seu email
const FORMSPREE_ENDPOINT="https://formspree.io/f/xgawylnr";
const fmt=(v?:string|string[])=>Array.isArray(v)?v.join(" · ")||"Não informado":String(v||"").trim()||"Não informado";
const buildPayload=(a:A)=>{
  const out:Record<string,string>={_subject:"Novo briefing recebido — Naming & Identidade"};
  S.forEach(s=>s.q.forEach(q=>{
    const key=`${String(q.n).padStart(2,"0")} — ${q.t}`;
    let val:string;
    if(q.type==="grouped"){val=q.groups?.map(g=>`${g.name}: ${fmt(a[`${q.id}_${g.name}`])}`).join(" · ")||"";}
    else if(q.none&&a[`${q.id}_none`]==="true"){val=q.none;}
    else{const other=a[`${q.id}_other`];val=fmt(a[q.id])+(other?` — ${other}`:"");}
    out[key]=val;
  }));
  if(String(a.refs||"").trim())out["Referências"]=fmt(a.refs);
  if(String(a.refsWhy||"").trim())out["O que gosta nessas referências"]=fmt(a.refsWhy);
  return out;
};
export default function Home(){const[screen,setScreen]=useState<"intro"|"form"|"review"|"sent">("intro"),[step,setStep]=useState(0),[a,setA]=useState<A>({}),[err,setErr]=useState<string[]>([]),[ready,setReady]=useState(false),[sending,setSending]=useState(false),[sendErr,setSendErr]=useState("");
useEffect(()=>{try{const x=localStorage.getItem(KEY);if(x)setA(JSON.parse(x))}catch{}setReady(true)},[]);useEffect(()=>{if(ready)localStorage.setItem(KEY,JSON.stringify(a))},[a,ready]);
const sec=S[step],set=(id:string,v:string|string[])=>{setA(x=>({...x,[id]:v}));setErr(x=>x.filter(e=>e!==id))},toggle=(q:Q,o:string)=>{const c=Array.isArray(a[q.id])?a[q.id] as string[]:[];c.includes(o)?set(q.id,c.filter(x=>x!==o)):(!q.max||c.length<q.max)&&set(q.id,[...c,o])};
const valid=(q:Q)=>{if(!q.req)return true;if(q.type==="grouped")return !!q.groups?.every(g=>a[`${q.id}_${g.name}`]);if(q.none&&a[`${q.id}_none`]==="true")return true;return Array.isArray(a[q.id])?a[q.id].length>0:!!String(a[q.id]||"").trim()},next=()=>{const m=sec.q.filter(q=>!valid(q)).map(q=>q.id);if(m.length){setErr(m);document.getElementById(m[0])?.scrollIntoView({behavior:"smooth",block:"center"});return}window.scrollTo({top:0,behavior:"smooth"});step<2?setStep(step+1):setScreen("review")},edit=(i:number)=>{setStep(i);setScreen("form");window.scrollTo({top:0,behavior:"smooth"})};
const handleSend=async()=>{
  setSending(true);setSendErr("");
  try{
    const res=await fetch(FORMSPREE_ENDPOINT,{method:"POST",headers:{"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify(buildPayload(a))});
    if(!res.ok)throw new Error("Falha no envio");
    localStorage.removeItem(KEY);setScreen("sent");window.scrollTo(0,0);
  }catch{
    setSendErr("Não consegui enviar agora. Verifique sua conexão e tente novamente.");
  }finally{
    setSending(false);
  }
};
if(screen==="intro")return <Intro start={()=>setScreen("form")} draft={Object.keys(a).length>0}/>;if(screen==="sent")return <Success/>;const progress=screen==="review"?100:Math.round(step/3*100);
return <main><header className="top"><button onClick={()=>setScreen("intro")}>BRIEFING <i>✦</i></button><div><span>{screen==="review"?"Revisão final":`Etapa 0${step+1} de 03`}</span><b>{progress}%</b></div></header><div className="bar"><i style={{width:progress+"%"}}/></div>{screen==="form"?<div className="layout" key={step}><aside><b>0{step+1}</b><div><small>{sec.label}</small><h1>{sec.name}</h1><p>{sec.intro}</p></div></aside><section className="questions">{step===2&&<div className="naming-transition"><small>NOVO CAPÍTULO</small><h2>AGORA VAMOS FALAR<br/><em>SOBRE O NOME.</em></h2><p>{sec.intro}</p></div>}{sec.q.map(q=><Question key={q.id} q={q} a={a} error={err.includes(q.id)} set={set} toggle={o=>toggle(q,o)}/>)}{step===2&&<References a={a} set={set}/>}<nav><button className="back" onClick={()=>step?edit(step-1):setScreen("intro")}>← VOLTAR</button><button className="primary" onClick={next}>{step===2?"REVISAR RESPOSTAS":"PRÓXIMA ETAPA"} <b>→</b></button></nav><footer>✓ Suas respostas são salvas automaticamente neste dispositivo.</footer></section></div>:<Review a={a} edit={edit} send={handleSend} sending={sending} sendErr={sendErr}/>}</main>}
function Intro({start,draft}:{start:()=>void;draft:boolean}){return <main className="intro"><header><span>BRIEFING</span><span>NAMING</span></header><div className="orb"><i>✦</i></div><section><small>UM NOVO COMEÇO</small><h1>VAMOS CONSTRUIR<br/><em>SUA MARCA.</em></h1><div className="intro-info"><p>Antes de pensar no nome, precisamos entender o que essa empresa precisa representar.</p><div><small>Tempo estimado</small><b>5–8 minutos</b></div></div><button onClick={start}>{draft?"CONTINUAR BRIEFING":"COMEÇAR"} <b>→</b></button></section><footer><span>01 — 03 ETAPAS</span><span>Briefing de naming</span></footer></main>}
function Question({q,a,error,set,toggle}:{q:Q;a:A;error:boolean;set:(id:string,v:string|string[])=>void;toggle:(o:string)=>void}){const value=a[q.id],none=a[`${q.id}_none`]==="true";return <article id={q.id} className={(error?"error ":"")+(q.featured?"featured":"")}><header><b>{String(q.n).padStart(2,"0")}</b><div><h2>{q.t} {q.req&&<sup>*</sup>}</h2>{q.h&&<p>{q.h}</p>}</div></header>{q.type==="single"||q.type==="multi"?<div className={"choices "+(q.desc?"described":"")}>{q.o?.map((o,i)=>{const sel=Array.isArray(value)?value.includes(o):value===o;return <button key={o} className={sel?"selected":""} onClick={()=>q.type==="single"?set(q.id,o):toggle(o)}><span><strong>{o}</strong>{q.desc?.[i]&&<small>{q.desc[i]}</small>}</span><b>{sel?"✓":"+"}</b></button>})}{q.max&&<p className="selection-count">{Array.isArray(value)?value.length:0} de {q.max} escolhidas</p>}</div>:q.type==="grouped"?<div className="answer-groups">{q.groups?.map(g=><div key={g.name}><small>{g.name}</small><div className="choices">{g.o.map(o=>{const id=`${q.id}_${g.name}`,sel=a[id]===o;return <button key={o} className={sel?"selected":""} onClick={()=>set(id,o)}><span>{o}</span><b>{sel?"✓":"+"}</b></button>})}</div></div>)}</div>:<><textarea disabled={none} value={none?"":String(value||"")} placeholder={none?"Opção selecionada":q.p} onChange={e=>set(q.id,e.target.value)}/>{q.none&&<button className={"none-choice "+(none?"selected":"")} onClick={()=>{set(`${q.id}_none`,none?"false":"true");if(!none)set(q.id,"")}}><b>{none?"✓":"+"}</b>{q.none}</button>}</>}{q.other&&Array.isArray(value)&&value.some(v=>v==="Outro"||v==="Outra palavra")&&<input className="other-input" value={String(a[`${q.id}_other`]||"")} placeholder="Escreva aqui..." onChange={e=>set(`${q.id}_other`,e.target.value)}/>} {error&&<p className="msg">Preencha esta resposta para continuar.</p>}</article>}
function References({a,set}:{a:A;set:(id:string,v:string|string[])=>void}){return <article className="references"><header><b>✦</b><div><small>REFERÊNCIAS — OPCIONAL</small><h2>Quer me mostrar alguma referência?</h2><p>Se tiver nomes de empresas ou marcas que você gosta, pode deixar aqui. Não precisam ser marcas de contabilidade.</p></div></header><textarea value={String(a.refs||"")} placeholder="Nomes de marcas ou empresas..." onChange={e=>set("refs",e.target.value)}/><label>O que você gosta nesses nomes?</label><textarea value={String(a.refsWhy||"")} placeholder="Ex.: são curtos, sofisticados, fáceis de lembrar..." onChange={e=>set("refsWhy",e.target.value)}/></article>}
function Review({a,edit,send,sending,sendErr}:{a:A;edit:(i:number)=>void;send:()=>void;sending:boolean;sendErr:string}){const ans=(q:Q)=>{if(q.type==="grouped")return q.groups?.map(g=>`${g.name}: ${fmt(a[`${q.id}_${g.name}`])}`).join(" · ");if(q.none&&a[`${q.id}_none`]==="true")return q.none;const x=a[`${q.id}_other`];return fmt(a[q.id])+(x?` — ${x}`:"")};return <div className="review"><header><small>ÚLTIMA ETAPA</small><h1>Revise suas<br/><em>respostas.</em></h1><p>Confira se está tudo certo antes de enviar.</p></header><section>{S.map((s,i)=><article key={s.name}><header><div><b>0{i+1}</b><h2>{s.name}</h2></div><button onClick={()=>edit(i)}>EDITAR ↗</button></header><div>{s.q.map(q=><p key={q.id}><small>{q.n}. {q.t}</small><b>{ans(q)}</b></p>)}</div></article>)}</section><footer><div><b>✦</b><p>{sendErr?<span className="msg" style={{marginLeft:0}}>{sendErr}</span>:"Com essas respostas, já consigo começar a explorar os primeiros caminhos para o nome."}</p></div><button className="primary" onClick={send} disabled={sending} style={sending?{opacity:.6,cursor:"wait"}:undefined}>{sending?"ENVIANDO...":"ENVIAR BRIEFING"} <b>→</b></button></footer></div>}
function Success(){return <main className="success"><i>✦</i><small>BRIEFING ENVIADO</small><h1>PRONTO.<br/><em>AGORA É COMIGO.</em> ✦</h1><div><p>Com essas respostas já consigo entender melhor o negócio e começar a explorar os primeiros caminhos para o nome da sua marca.</p><p>Vou analisar tudo com calma e seguir para a etapa de direcionamento e naming.</p></div><footer><span/><b>01</b><span/></footer></main>}
